### ISSUE TITLE
Support other pointcloud formats -- updating easy3d third party

### ISSUE THREAD

**Issue by Tofull** [tudelft3d/AdTree#10]
Hi, 

AdTree is currently limited to .xyz pointcloud format only, but it uses easy3d to load the pointcloud data.
However, many formats are already supported by [the latest version of easy3d](https://github.com/LiangliangNan/Easy3D/blob/f5e850aed245095f713778a7d9df2141c509dc48/easy3d/fileio/point_cloud_io.cpp#L50-L64).

I would like to know if we can update the third-party easy3d to use the latest version of easy3D ? I can understand this migration could affect other functions used in AdTree.

**Comment by LiangliangNan** [comment]
A lot of changes have been made to Easy3D since the release of AdTree. The version of Easy3D used in AdTree is not compatible with the latest version anymore. 
The update is possible, but it requires modifying the code in many places (viewer, camera, fileio, renderer ...). I don't see it is necessary for such an update. Of course, if you like, you can strip the fileio part from Easy3D and integrate it into AdTree. 
Considering that AdTree is just a prototype demonstrating the algorithm, I would keep it as minimum as possible.
