### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by Gweiqi** [tudelft3d/AdTree#11]
Dear Developers.
I have my own skeleton file and information about the diameters at different locations, and I would like to use this software to generate him as a tree without leaves. In fact, I am trying to develop an airway model, which is actually very much like a tree. I have calculated its skeleton and its width at different locations. But I am not very good at programming and I need your help.
![image](https://user-images.githubusercontent.com/45964355/150524565-f51951e1-443b-4003-9e32-bba7636f4db5.png)
All the best,
GuoWeiqi

**Comment by LiangliangNan** [comment]
Since you've already obtained the skeleton (with the radius information), you can then extract a surface mesh to represent the tree geometry.
This is implemented in `bool Skeleton::extract_branch_surfaces(SurfaceMesh* result)` (line 1462 in `skeleton.cpp`). You first need to store the nodes and their corresponding radii in the Branch structure, as shown in line 1464 in `skeleton.cpp`:   `const std::vector<Branch>& branches = ...`. Then for each branch, you call the `add_generalized_cylinder_to_model(...)` function to extract its surface.

**Comment by LiangliangNan** [comment]
I believe the problem has been solved, so I am going to close this issue.
Feel free to reopen it when this is not the case.
Good luck with your research!
