### ISSUE TITLE
change the leaves

### ISSUE THREAD

**Issue by daofeng2007** [tudelft3d/AdTree#15]
Thanks to the author for sharing this software, which is very useful. Right now, it seems all the trees use the same type of leaf. I am wondering if the author can add the feature to change the leaves, e.g., the density of the leaves, the shape of the leaves etc.

**Comment by LiangliangNan** [comment]
Thanks for your kind words and suggestion!
The code in this repository is the research prototype demonstrating the algorithm presented in the AdTree paper. Since the paper focuses on skeleton (NOT leaf) generation, we don't see the necessity to provide different types of leaves. 
But we'd be happy to see similar ideas implemented in any user's forked branches.
